CREATE DATABASE DULICH
USE DULICH
CREATE TABLE LOAITOUR
(
	MALOAI NVARCHAR(10) PRIMARY KEY,
	TENLOAI NVARCHAR(20)
)
GO
CREATE TABLE DIADIEM
(
	MADIADIEM NVARCHAR(10) PRIMARY KEY,
	TENDD NVARCHAR(20)
)
GO
CREATE TABLE CTTOUR
(
	THUTU INT,
	MATOUR NVARCHAR(10),
	MADD NVARCHAR(10),
	PRIMARY KEY (MATOUR,MADD)
) 
CREATE TABLE TOUR
(
	MATOUR NVARCHAR(10) PRIMARY KEY,
	TENTOUR NVARCHAR(50),
	DACDIEM NVARCHAR(50),
	MALOAI NVARCHAR(10)
)
GO
CREATE TABLE GIATOUR
(
	MAGIA NVARCHAR(10) PRIMARY KEY,
	GIATIEN FLOAT,
	TGBD DATE,
	TGKT DATE,
	MATOUR NVARCHAR(10)
)
CREATE TABLE DOAN
(
	MADOAN NVARCHAR(10) PRIMARY KEY,
	NGAYBD DATE,
	NGAYKT DATE,
	MATOUR NVARCHAR(10)
)
CREATE TABLE CHIPHI 
(
	MACP NVARCHAR(10) PRIMARY KEY,
	MALOAICP NVARCHAR(10),
	MADOAN NVARCHAR(10),
	GIATRI FLOAT
)
CREATE TABLE LOAICP
(
	MALOAICP NVARCHAR(10) PRIMARY KEY,
	TENLOAICP NVARCHAR(50)
)
CREATE TABLE KHACH
(
	MAKHACH NVARCHAR(10) PRIMARY KEY,
	HOTEN NVARCHAR(50),
	CMND NVARCHAR(10),
	GIOITINH NVARCHAR(10),
	SDT NVARCHAR(10)
)
CREATE TABLE CHITIETDOAN
(
	MADOAN NVARCHAR(10),
	MAKHACH NVARCHAR(10)
)
GO
CREATE TABLE NVTHUOCDOAN
(
	MADOAN NVARCHAR(10),
	MANV NVARCHAR(10),
	NHIEMVU NVARCHAR(50),
	GHICHU NVARCHAR(50)
)
CREATE TABLE NHANVIEN
(
	MANV NVARCHAR(10) PRIMARY KEY,
	TENNV NVARCHAR(50)
)

--DAT KHOA NGOAI---------------
ALTER TABLE TOUR ADD CONSTRAINT fk_maloai FOREIGN KEY(MALOAI) REFERENCES LOAITOUR(MALOAI)
ALTER TABLE dbo.CTTOUR ADD CONSTRAINT fk_matour FOREIGN KEY(MATOUR) REFERENCES TOUR(MATOUR)
ALTER TABLE dbo.CTTOUR ADD CONSTRAINT fk_madd FOREIGN KEY(MADD) REFERENCES dbo.DIADIEM(MADIADIEM)	
ALTER TABLE dbo.GIATOUR ADD CONSTRAINT fk_giatour FOREIGN KEY(MATOUR) REFERENCES dbo.TOUR(MATOUR)
ALTER TABLE dbo.CHIPHI ADD CONSTRAINT fk_cp1 FOREIGN KEY(MADOAN) REFERENCES dbo.DOAN(MADOAN)
ALTER TABLE dbo.CHIPHI ADD CONSTRAINT fk_cp2 FOREIGN KEY(MALOAICP) REFERENCES dbo.LOAICP(MALOAICP)
ALTER TABLE dbo.CHITIETDOAN ADD CONSTRAINT fk_ctdoan1 FOREIGN KEY(MADOAN) REFERENCES dbo.DOAN(MADOAN)
ALTER TABLE dbo.CHITIETDOAN ADD CONSTRAINT fk_ctdoan2 FOREIGN KEY(MAKHACH) REFERENCES dbo.KHACH(MAKHACH)
ALTER TABLE dbo.NVTHUOCDOAN ADD CONSTRAINT pk_nvthuocdoan PRIMARY KEY(MADOAN,MANV)
ALTER TABLE dbo.NVTHUOCDOAN ADD CONSTRAINT fk_nvthuocdoan FOREIGN KEY(MADOAN) REFERENCES dbo.DOAN(MADOAN)
ALTER TABLE dbo.NVTHUOCDOAN ADD CONSTRAINT fk_nvthuocdoan1 FOREIGN KEY(MANV) REFERENCES dbo.NHANVIEN(MANV)
ALTER TABLE dbo.CHITIETDOAN ADD CONSTRAINT pk_ctdoan PRIMARY KEY (MADOAN,MAKHACH)
ALTER TABLE dbo.CHIPHI ADD CONSTRAINT pk_cp PRIMARY KEY(MALOAICP,MADOAN) 

SELECT* FROM dbo.CHITIETDOAN
SELECT* FROM dbo.KHACH
SELECT* FROM dbo.CTTOUR
SELECT* FROM dbo.LOAITOUR
SELECT* FROM dbo.TOUR

SELECT* FROM dbo.DIADIEM
SELECT* FROM dbo.GIATOUR
SELECT* FROM dbo.NHANVIEN
SELECT* FROM dbo.DOAN
SELECT* FROM dbo.NVTHUOCDOAN


SELECT td.NHIEMVU, d.MATOUR, d.MADOAN,t.TENTOUR 
FROM dbo.DOAN d, dbo.NHANVIEN n, dbo.NVTHUOCDOAN td, dbo.TOUR t
WHERE NGAYBD BETWEEN '2020-04-20' AND '2020-06-21' AND d.MADOAN=td.MADOAN AND td.MANV = n.MANV AND n.MANV='NV003' AND t.MATOUR = d.MATOUR

SELECT COUNT(d.MADOAN) AS TONGSO, n.TENNV
FROM dbo.DOAN d, dbo.NHANVIEN n, dbo.NVTHUOCDOAN td, dbo.TOUR t
WHERE NGAYBD BETWEEN '2020-04-20' AND '2020-06-21' AND d.MADOAN=td.MADOAN AND td.MANV = n.MANV AND n.MANV='NV003' AND t.MATOUR = d.MATOUR
GROUP BY n.TENNV

SELECT SUM(c.GIATRI) AS TONGCHIPHI, t.TENTOUR
FROM dbo.DOAN d, dbo.TOUR t, dbo.CHIPHI c, dbo.LOAICP l
WHERE t.MATOUR=d.MATOUR AND d.MADOAN=c.MADOAN AND c.MALOAICP=l.MALOAICP AND t.MATOUR='T001'
GROUP BY t.TENTOUR

SELECT* FROM dbo.CHIPHI c, dbo.LOAICP l
WHERE c.MALOAICP = l.MALOAICP

SELECT d.MADOAN
FROM dbo.TOUR t, dbo.DOAN d
WHERE t.MATOUR = d.MATOUR AND d.NGAYBD BETWEEN '2020-05-01' AND '2020-07-22' AND d.MATOUR = 'T002' 

SELECT c.GIATRI, d.MADOAN, t.MATOUR
FROM dbo.CHIPHI c, dbo.LOAICP l, dbo.DOAN d, dbo.TOUR t
WHERE l.MALOAICP=c.MALOAICP AND d.MADOAN = c.MADOAN AND d.MATOUR = 'T002' AND d.NGAYBD BETWEEN '2020-05-01' AND '2020-07-22' AND t.MATOUR=d.MATOUR

SELECT c.GIATRI, d.MADOAN, t.MATOUR
FROM dbo.CHIPHI c, dbo.LOAICP l, dbo.DOAN d, dbo.TOUR t
WHERE l.MALOAICP=c.MALOAICP AND d.MADOAN = c.MADOAN AND d.MATOUR = 'T002' AND d.NGAYBD BETWEEN '2020-05-01' AND '2020-07-22' AND t.MATOUR=d.MATOUR AND d.MADOAN = 'D002'


SELECT d.MADOAN, d.NGAYBD, d.NGAYKT, COUNT(ctd.MAKHACH) AS TONGSOKHACH, g.GIATIEN, SUM(c.GIATRI) AS TONGCHIPHI, (COUNT(ctd.MAKHACH)*g.GIATIEN) AS TONGTHU, ((COUNT(ctd.MAKHACH)*g.GIATIEN) - SUM(c.GIATRI)) AS DOANHTHU
FROM dbo.DOAN d, dbo.KHACH k, dbo.CHITIETDOAN ctd, dbo.GIATOUR g, dbo.TOUR t, dbo.CHIPHI c
WHERE d.MADOAN = ctd.MADOAN AND ctd.MAKHACH = k.MAKHACH AND g.MATOUR = t.MATOUR AND t.MATOUR = d.MATOUR AND c.MADOAN = d.MADOAN AND d.NGAYBD <'2020/11/04' AND d.NGAYKT >= '2020/04/04' AND d.NGAYBD > g.TGBD AND d.NGAYBD <=g.TGKT AND t.MATOUR = 'T002'
GROUP BY d.MADOAN, d.NGAYBD, d.NGAYKT, g.GIATIEN


SELECT d.MADOAN, COUNT(ctd.MAKHACH) AS TONGSOKHACH, g.GIATIEN
FROM dbo.DOAN AS d JOIN dbo.TOUR AS t ON d.MATOUR = t.MATOUR
		JOIN dbo.GIATOUR AS g ON g.MATOUR = t.MATOUR
		JOIN dbo.CHITIETDOAN AS ctd ON ctd.MADOAN = d.MADOAN
WHERE d.NGAYBD <'2020/11/04' AND d.NGAYKT >= '2020/04/04' AND d.NGAYBD > g.TGBD AND d.NGAYBD <=g.TGKT AND t.MATOUR = 'T002'
GROUP BY d.MADOAN, g.GIATIEN


SELECT d.MADOAN, d.NGAYBD, d.NGAYKT, COUNT(ctd.MAKHACH) AS TONGSOKHACH, g.GIATIEN--, SUM(c.GIATRI) AS TONGCHIPHI
FROM dbo.TOUR t, dbo.DOAN d, dbo.GIATOUR g, dbo.CHITIETDOAN ctd--, dbo.CHIPHI c
WHERE d.MATOUR = t.MATOUR AND t.MATOUR = g.MATOUR AND ctd.MADOAN = d.MADOAN
		--AND c.MADOAN = d.MADOAN
		AND d.NGAYBD <'2020/11/04' AND d.NGAYKT >= '2020/04/04' 
		AND d.NGAYBD > g.TGBD AND d.NGAYBD <=g.TGKT 
		AND t.MATOUR = 'T002'
GROUP BY d.MADOAN, g.GIATIEN, d.NGAYBD, d.NGAYKT


SELECT d.MADOAN, d.NGAYBD, d.NGAYKT, COUNT(ctd.MAKHACH) AS TONGSOKHACH, g.GIATIEN, SUM(c.GIATRI) AS TONGCHIPHI
FROM dbo.TOUR t, dbo.DOAN d, dbo.GIATOUR g, dbo.CHITIETDOAN ctd, dbo.CHIPHI c
WHERE d.MATOUR = t.MATOUR 
		AND t.MATOUR = g.MATOUR 
		AND ctd.MADOAN = d.MADOAN
		AND c.MADOAN = d.MADOAN
		AND d.NGAYBD <'2020/11/04' AND d.NGAYKT >= '2020/04/04' 
		AND d.NGAYBD > g.TGBD AND d.NGAYBD <=g.TGKT 
		AND t.MATOUR = 'T002'
GROUP BY d.MADOAN, g.GIATIEN, d.NGAYBD, d.NGAYKT

SELECT DISTINCT COUNT(ct.MAKHACH) AS TONGKHACH, d.MADOAN, SUM(c.GIATRI)
FROM dbo.DOAN d, dbo.CHITIETDOAN ct, dbo.CHIPHI c
WHERE d.MADOAN = c.MADOAN AND d.MADOAN = ct.MADOAN
GROUP BY d.MADOAN

SELECT COUNT(*) AS TONGKHACH, d.MADOAN INTO #tam
FROM dbo.CHITIETDOAN ct, dbo.DOAN d, dbo.TOUR t
WHERE ct.MADOAN = d.MADOAN AND t.MATOUR = 'T002' AND t.MATOUR = d.MATOUR
GROUP BY d.MADOAN


--SELECT SUM(c.GIATRI) AS TONGCHI, #tam.MADOAN, TONGKHACH
--FROM #tam, dbo.CHIPHI c
--WHERE c.MADOAN = #tam.MADOAN
--GROUP BY #tam.MADOAN, TONGKHACH

SELECT #tam.MADOAN, d.NGAYBD, d.NGAYKT,  #tam.TONGKHACH, g.GIATIEN, (g.GIATIEN*#tam.TONGKHACH) AS TONGTHU, SUM(c.GIATRI) AS TONGCHI, ((g.GIATIEN*#tam.TONGKHACH) - SUM(c.GIATRI))AS DOANHTHU
FROM dbo.GIATOUR g, dbo.TOUR t, #tam, dbo.DOAN d, dbo.CHIPHI c
WHERE #tam.MADOAN = d.MADOAN AND d.MATOUR = t.MATOUR AND t.MATOUR = g.MATOUR AND c.MADOAN = #tam.MADOAN
		AND d.NGAYBD <'2020/11/04' AND d.NGAYKT >= '2020/04/04' 
		AND d.NGAYBD > g.TGBD AND d.NGAYBD <=g.TGKT 
		AND t.MATOUR = 'T002'
GROUP BY  #tam.MADOAN, #tam.TONGKHACH, (g.GIATIEN*#tam.TONGKHACH), g.GIATIEN, d.NGAYBD, d.NGAYKT

SELECT #tam.MADOAN, #tam.TONGKHACH, ((g.GIATIEN*#tam.TONGKHACH) - SUM(c.GIATRI))AS DOANHTHU, t.TENTOUR
FROM dbo.GIATOUR g, dbo.TOUR t, #tam, dbo.DOAN d, dbo.CHIPHI c
WHERE #tam.MADOAN = d.MADOAN AND d.MATOUR = t.MATOUR AND t.MATOUR = g.MATOUR AND c.MADOAN = #tam.MADOAN
		AND d.NGAYBD > g.TGBD AND d.NGAYBD <=g.TGKT 
		AND t.MATOUR = 'T002'
GROUP BY #tam.MADOAN, g.GIATIEN, #tam.TONGKHACH, t.TENTOUR

SELECT* FROM #tam
DROP TABLE #tam



--------------------------------------------------------------
